import Link from "next/link";
import { Arrow, DemoNotice, StampCard } from "@/components/ui";
import { ImpactCalculator } from "@/components/impact-calculator";
const business = { name: "Votre commerce" };

export default function Home() {
  return <>
    <section className="hero"><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-line"/> LA FIDÉLITÉ QUI SE VIT</div><h1>Donnez une raison<br/>de <em>revenir.</em></h1><p>Une carte digitale simple à rejoindre. Des points à chaque visite. Une récompense que vos clients ont envie de retrouver.</p><div className="actions"><Link className="button dark" href="/business/login"><Arrow>Créer mon programme</Arrow></Link><Link className="text-link" href="#comment-ca-marche">Voir comment ça marche →</Link></div><div className="hero-proof"><span className="proof-icon">✳</span><span>Un programme à créer pour votre commerce, sans application à installer.</span></div></div><div className="hero-art"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="floating-label top">✦ &nbsp; Votre carte, toujours à portée de main</div><div className="preview-card"><div className="preview-top"><span>PROGRAMME DE FIDÉLITÉ</span><span>✳</span></div><div className="preview-business">{business.name}</div><div className="preview-sub">Chaque visite vous rapproche d’une récompense.</div><StampCard visits={5}/><div className="preview-bottom"><span>50 / 80 POINTS</span><span>Encore 30 points ↗</span></div></div><div className="floating-label bottom">🎁 &nbsp; Une récompense à 80 points</div></div></div></section>
    <section className="section value-section"><div className="container"><span className="kicker">POURQUOI FIDELI</span><h2>Une belle expérience pour vos clients.<br/><em>Une vraie vue d’ensemble pour vous.</em></h2><div className="value-grid"><article><span>01</span><h3>Facile à rejoindre</h3><p>Le client scanne votre QR code et découvre sa carte depuis son téléphone.</p></article><article><span>02</span><h3>Facile à utiliser</h3><p>Vous validez la visite dans l’espace commerçant. Le client voit progresser ses points.</p></article><article><span>03</span><h3>Facile à comprendre</h3><p>Une récompense claire et un parcours simple à lancer pour votre commerce.</p></article></div></div></section>
    <section id="comment-ca-marche" className="section process-section"><div className="container"><div className="section-heading"><div><span className="kicker">EN TROIS ÉTAPES</span><h2>Du premier scan<br/>à la <em>prochaine visite.</em></h2></div><p>Découvrez le parcours d’inscription, de validation en caisse et de récompense.</p></div><div className="process-grid"><article><span className="process-number">01</span><div className="process-symbol">▦</div><h3>Partagez le QR code</h3><p>Un lien et un QR code depuis l’espace commerçant.</p></article><article><span className="process-number">02</span><div className="process-symbol">✳</div><h3>Accueillez le client</h3><p>Il reçoit un lien email pour retrouver sa carte.</p></article><article><span className="process-number">03</span><div className="process-symbol">✦</div><h3>Récompensez ses visites</h3><p>Ajoutez des points et testez l’utilisation d’une récompense.</p></article></div></div></section>
    <section className="section impact-section"><div className="container"><div className="section-heading"><div><span className="kicker">PROJETEZ-VOUS</span><h2>Faites le calcul<br/><em>avec vos chiffres.</em></h2></div><p>Explorez différents scénarios de fréquentation. Vos chiffres restent sur cette page.</p></div><ImpactCalculator/><div className="impact-cta"><div><h3>Essayez avec votre commerce.</h3><p>Créez votre espace et personnalisez votre premier programme de fidélité.</p></div><Link className="button dark" href="/business/login">Créer mon espace →</Link></div></div></section>
    <section className="section features-section"><div className="container"><span className="kicker">UNE BASE CONCRÈTE</span><h2>Ce que vous pouvez <em>tester.</em></h2><div className="feature-grid"><article><span>▦</span><h3>QR code à partager</h3><p>Ouvrez le parcours client depuis une affiche ou un lien.</p></article><article><span>✳</span><h3>Points et récompense</h3><p>Enregistrez les visites et suivez la progression de la carte.</p></article><article><span>♡</span><h3>Retour client privé</h3><p>Le client peut donner une note privée après une visite et recevoir des points.</p></article><article><span>◫</span><h3>Wallet en option</h3><p>À venir après la synchronisation sécurisée des points.</p></article></div></div></section>
    <section className="section pricing-section"><div className="container pricing-grid"><div><span className="kicker">TARIFS ENVISAGÉS</span><h2>Un prix simple, <em>par commerce.</em></h2><p>Tarifs indicatifs pour la phase de lancement, à confirmer avant toute souscription. Aucun paiement n’est encore proposé dans cette version.</p></div><div className="pricing-card"><span>OFFRE ENVISAGÉE</span><strong>À partir de 19 € <small>HT / mois</small></strong><p>Carte digitale, QR code, points et tableau de bord. Le coût des cartes physiques et des services Wallet sera précisé séparément.</p><Link className="button dark" href="/business/login">Essayer avec mon commerce →</Link></div></div></section>
    <section className="section cta-section"><div className="container cta-grid"><div><span className="kicker">PRÊT À ESSAYER ?</span><h2>Voyez Fideli<br/><em>en action.</em></h2><p>Découvrez le parcours puis créez votre propre espace commerçant.</p><Link className="button cream" href="/demo"><Arrow>Découvrir le parcours</Arrow></Link></div><div className="cta-symbol" aria-hidden>✳</div></div></section><div className="container notice-wrap"><DemoNotice/></div>
  </>;
}
